export {default as Home} from './Home/Home.tsx'
export {default as About} from './About/about-us.tsx'
export {default as FAQ} from './FAQ/faq.tsx'
export {default as Contact} from './Contact/contact.tsx'
export {default as Tutor} from './Tutor/become-a-tutor.tsx'